server:
  port: 8082

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5442/local-chat-db
      username: chat_user
      password: chat_password
      connection-test-query: SELECT 1
